on: push

name: deploy production
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 2

      - name: 📂 Sync files
        uses: bhartiyablog/FTP-Deploy-Action@4.0.0
        with:
          server: bhartiyablog.com
          username: mohan@bhartiyablog.com
          password: ${{ secrets.ftp_password }}
          port: 21
          server-dir: ./rohit